#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');
const OUTPUT = path.join(DOCS, 'index', 'README.md');
const mode = process.argv[2];
if (!['--check', '--write'].includes(mode) || process.argv.length !== 3) {
  console.error('Usage: node scripts/generate_docs_index.js --check|--write');
  process.exit(2);
}
const EXCLUDED_DIRECTORIES = new Set(['AbyssalCraft-1.12.2', 'validation']);
const EXCLUDED_FILES = new Set([
  'index/README.md', 'porting/01-porting-task-plan.md',
  'porting/02-porting-parallel-tasks.md', 'porting/03-user-validation-plan.md',
]);

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const target = path.join(directory, entry.name);
    const relative = path.relative(DOCS, target).replaceAll('\\', '/');
    if (entry.isDirectory()) {
      if (EXCLUDED_DIRECTORIES.has(entry.name) || /(?:^|\/)(?:build|run)(?:\/|$)/.test(relative)) return [];
      return walk(target);
    }
    if (!entry.name.endsWith('.md') || EXCLUDED_FILES.has(relative) || /(?:^|\/)U-[^/]*\.md$/i.test(relative)) return [];
    return [relative];
  });
}

function title(file) {
  const line = fs.readFileSync(path.join(DOCS, file), 'utf8').split(/\r?\n/)
    .find(candidate => /^#\s+\S/.test(candidate));
  return line ? line.replace(/^#\s+/, '').trim() : path.basename(file, '.md');
}

const files = walk(DOCS).sort((left, right) => left.localeCompare(right, 'en'));
const groups = new Map();
for (const file of files) {
  const directory = path.posix.dirname(file);
  if (!groups.has(directory)) groups.set(directory, []);
  groups.get(directory).push(file);
}
const lines = [
  '# Documentation Index', '',
  '<!-- Generated by scripts/generate_docs_index.js. Do not edit by hand. -->', '',
  'This index contains maintained design and subsystem documentation. Build output, runtime data,',
  'legacy source mirrors, validation evidence, and U-lane evidence are intentionally excluded.', '',
];
for (const [directory, entries] of groups) {
  lines.push(`## ${directory === '.' ? 'Top level' : directory}`, '');
  for (const file of entries) {
    const link = path.posix.relative('index', file);
    lines.push(`- [${title(file)}](${link})`);
  }
  lines.push('');
}
const generated = `${lines.join('\n').trimEnd()}\n`;
if (mode === '--write') {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, generated);
  console.log(`R8_DOCS_INDEX_WRITE_OK files=${files.length} output=docs/index/README.md`);
} else if (!fs.existsSync(OUTPUT)) {
  console.error('R8_DOCS_INDEX_CHECK_FAILED reason=missing docs/index/README.md');
  process.exitCode = 1;
} else if (fs.readFileSync(OUTPUT, 'utf8').replace(/\r\n/g, '\n') !== generated) {
  console.error('R8_DOCS_INDEX_CHECK_FAILED reason=stale docs/index/README.md; run with --write');
  process.exitCode = 1;
} else {
  console.log(`R8_DOCS_INDEX_CHECK_OK files=${files.length} output=docs/index/README.md`);
}