#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { readPng, writePng } = require('./png_rgba');

const ROOT = path.resolve(__dirname, '..');
const MODERN_ROOT = path.join(ROOT, 'src/main/resources/assets/abyssalcraft');
const GENERATED_ROOT = path.join(ROOT, 'src/main/generated/assets/abyssalcraft');
const LEGACY_ROOT = path.join(ROOT,
    'docs/AbyssalCraft-1.12.2/src/main/resources/assets/abyssalcraft');
const LEGACY_JAVA_ROOT = path.join(ROOT, 'docs/AbyssalCraft-1.12.2/src/main/java');
const ASSET_ARCHIVE = path.join(ROOT, 'src/main/resources/assets.7z');
const ASSET_LEDGER = path.join(ROOT, 'docs/validation/RR-ASSET-SHA256.json');
const MANIFEST = path.join(ROOT, 'docs/validation/RR-RESTRICTED-ASSET-PLACEHOLDERS.json');
const MARKER = 'License-safe placeholder generated by scripts/replace_restricted_assets.js';
const mode = process.argv[2] || '--check';

if (!['--check', '--write'].includes(mode) || process.argv.length > 3) {
    console.error('Usage: node scripts/replace_restricted_assets.js [--check|--write]');
    process.exit(2);
}

const LICENSE_SAFE_TEXTURES = new Set(['textures/particle/abyssal_fx.png']);
const MODERN_JAVA_MODELS = [
    'src/main/java/com/shinoow/abyssalcraft/client/model/entity/DragonModel.java',
    'src/main/java/com/shinoow/abyssalcraft/client/model/entity/GhoulArmorModel.java',
    'src/main/java/com/shinoow/abyssalcraft/client/model/entity/GhoulModel.java',
];

function walk(directory) {
    if (!fs.existsSync(directory)) return [];
    return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
        const target = path.join(directory, entry.name);
        return entry.isDirectory() ? walk(target) : [target];
    });
}

function relative(file) {
    return path.relative(ROOT, file).replaceAll('\\', '/');
}

function relativeTo(file, root) {
    return path.relative(root, file).replaceAll('\\', '/');
}

function readJson(file) {
    return JSON.parse(fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, ''));
}

function stableJson(value) {
    return `${JSON.stringify(value, null, 2)}\n`;
}

function modernModelIsRestricted(file, name, ledgerEntries) {
    if (name.endsWith('.geo.json') || name.endsWith('.obj') || name.endsWith('.mtl')) return true;
    if (!name.startsWith('models/') || !name.endsWith('.json')) return false;
    if (ledgerEntries[name]?.source?.startsWith('legacy:')) return true;
    const model = readJson(file);
    return Array.isArray(model.elements)
        || model.loader === '__LOADER__:obj'
        || model.parent === 'abyssalcraft:block/legacy_custom_model'
        || (typeof model.credit === 'string'
            && /(?:AbyssalCraft 1\.12\.2|docs\/AbyssalCraft-1\.12\.2|legacy|faithful)/i.test(model.credit));
}

function discoverTargets() {
    const ledgerEntries = fs.existsSync(ASSET_LEDGER) ? readJson(ASSET_LEDGER).entries || {} : {};
    const targets = new Map();
    const add = (file, kind) => {
        const targetPath = relative(file);
        const existing = targets.get(targetPath);
        const target = { ...existing, path: targetPath, kind };
        if (!existing && fs.existsSync(file) && kind === 'texture-png') {
            const bytes = fs.readFileSync(file);
            target.width = bytes.readUInt32BE(16);
            target.height = bytes.readUInt32BE(20);
        }
        if (!existing && fs.existsSync(file) && kind === 'model-geo') {
            const geometry = readJson(file)['minecraft:geometry']?.[0];
            target.requiredBones = [...new Set((geometry?.bones || [])
                .map(bone => bone.name)
                .filter(name => typeof name === 'string' && name.length > 0))].sort();
        }
        if (fs.existsSync(file) && kind === 'sound-catalog' && !target.requiredEvents) {
            target.requiredEvents = Object.keys(readJson(file)).sort();
        }
        targets.set(targetPath, target);
    };

    if (fs.existsSync(MANIFEST)) {
        for (const target of readJson(MANIFEST).targets || []) {
            targets.set(target.path, target);
        }
    }

    for (const root of [MODERN_ROOT, GENERATED_ROOT]) {
        for (const file of walk(root)) {
            const name = relativeTo(file, root);
            if (name.startsWith('textures/') && name.endsWith('.png')) {
                if (!LICENSE_SAFE_TEXTURES.has(name)) add(file, 'texture-png');
            } else if (name.startsWith('textures/') && name.endsWith('.png.mcmeta')) {
                const texture = name.slice(0, -'.mcmeta'.length);
                if (!LICENSE_SAFE_TEXTURES.has(texture)) add(file, 'texture-metadata');
            } else if (name.startsWith('sounds/') && name.endsWith('.ogg')) {
                add(file, 'sound-ogg-removed');
            } else if (modernModelIsRestricted(file, name, ledgerEntries)) {
                if (name.endsWith('.geo.json')) add(file, 'model-geo');
                else if (name.endsWith('.obj')) add(file, 'model-obj');
                else if (name.endsWith('.mtl')) add(file, 'model-mtl');
                else if (name.endsWith('.json')) {
                    add(file, name.startsWith('models/item/') ? 'model-item-json' : 'model-block-json');
                }
            }
        }
    }

    const soundsFile = path.join(MODERN_ROOT, 'sounds.json');
    if (fs.existsSync(soundsFile)) add(soundsFile, 'sound-catalog');
    for (const model of MODERN_JAVA_MODELS) add(path.join(ROOT, model), 'modern-java-model');

    for (const name of Object.keys(ledgerEntries)) {
        if (name.startsWith('sounds/') && name.endsWith('.ogg')) {
            add(path.join(MODERN_ROOT, name), 'sound-ogg-removed');
        }
    }

    for (const file of walk(LEGACY_ROOT)) {
        const name = relativeTo(file, LEGACY_ROOT);
        if (name.startsWith('textures/') && name.endsWith('.png')) add(file, 'texture-png');
        else if (name.startsWith('textures/') && name.endsWith('.png.mcmeta')) add(file, 'texture-metadata');
        else if (name.startsWith('sounds/') && name.endsWith('.ogg')) add(file, 'sound-ogg-removed');
        else if (name.startsWith('models/') && name.endsWith('.obj')) add(file, 'model-obj');
        else if (name.startsWith('models/') && name.endsWith('.mtl')) add(file, 'model-mtl');
        else if (name.startsWith('models/') && name.endsWith('.json')) {
            add(file, name.startsWith('models/item/') ? 'model-item-json' : 'model-block-json');
        }
    }

    for (const file of walk(LEGACY_JAVA_ROOT).filter(candidate => candidate.endsWith('.java'))) {
        const source = fs.readFileSync(file, 'utf8');
        if (relativeTo(file, LEGACY_JAVA_ROOT).includes('/model/')
            || /new\s+ModelRenderer\s*\(/.test(source)) {
            add(file, 'legacy-java-model');
        }
    }

    if (fs.existsSync(ASSET_ARCHIVE)) add(ASSET_ARCHIVE, 'asset-archive-removed');

    return [...targets.values()].sort((left, right) => left.path.localeCompare(right.path));
}

function placeholderPng(file) {
    const bytes = fs.readFileSync(file);
    if (bytes.length < 24 || bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') {
        throw new Error(`Invalid PNG ${relative(file)}`);
    }
    const width = bytes.readUInt32BE(16);
    const height = bytes.readUInt32BE(20);
    const pixels = Buffer.alloc(width * height * 4);
    const cell = Math.max(1, Math.floor(Math.min(width, height) / 8));
    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const offset = (y * width + x) * 4;
            const bright = (Math.floor(x / cell) + Math.floor(y / cell)) % 2 === 0;
            pixels[offset] = bright ? 255 : 24;
            pixels[offset + 1] = bright ? 0 : 24;
            pixels[offset + 2] = bright ? 255 : 24;
            pixels[offset + 3] = 255;
        }
    }
    return { width, height, pixels };
}

function expectedJson(kind) {
    if (kind === 'model-item-json') {
        return stableJson({
            credit: MARKER,
            parent: 'minecraft:item/generated',
            textures: { layer0: 'minecraft:item/barrier' },
        });
    }
    return stableJson({
        credit: MARKER,
        parent: 'minecraft:block/cube_all',
        textures: { all: 'minecraft:block/magenta_wool' },
    });
}

function placeholderTextureMetadata() {
    return stableJson({ animation: { frametime: 1, frames: [0] } });
}

function placeholderGeo(file) {
    const source = readJson(file);
    const sourceGeometry = source['minecraft:geometry']?.[0] || {};
    const sourceDescription = sourceGeometry.description || {};
    const boneNames = [...new Set((sourceGeometry.bones || [])
        .map(bone => bone.name)
        .filter(name => typeof name === 'string' && name.length > 0))];
    return stableJson({
        format_version: '1.12.0',
        'minecraft:geometry': [{
            description: {
                identifier: 'geometry.abyssalcraft.placeholder',
                texture_width: sourceDescription.texture_width || 16,
                texture_height: sourceDescription.texture_height || 16,
                visible_bounds_width: 2,
                visible_bounds_height: 2,
                visible_bounds_offset: [0, 1, 0],
            },
            bones: [{
                name: 'placeholder_root',
                pivot: [0, 8, 0],
                cubes: [{ origin: [-4, 4, -4], size: [8, 8, 8], uv: [0, 0] }],
            }, ...boneNames.filter(name => name !== 'placeholder_root').map(name => ({
                name,
                parent: 'placeholder_root',
                pivot: [0, 0, 0],
            }))],
        }],
    });
}

function placeholderObj(file) {
    return `# ${MARKER}\n`
        + `mtllib ${path.basename(file, '.obj')}.mtl\n`
        + 'o placeholder_cube\n'
        + 'v -0.5 -0.5 -0.5\nv 0.5 -0.5 -0.5\nv 0.5 0.5 -0.5\nv -0.5 0.5 -0.5\n'
        + 'v -0.5 -0.5 0.5\nv 0.5 -0.5 0.5\nv 0.5 0.5 0.5\nv -0.5 0.5 0.5\n'
        + 'usemtl placeholder\n'
        + 'f 1 2 3 4\nf 5 8 7 6\nf 1 5 6 2\nf 2 6 7 3\nf 3 7 8 4\nf 5 1 4 8\n';
}

function placeholderMtl() {
    return `# ${MARKER}\nnewmtl placeholder\nKd 1.0 0.0 1.0\n`;
}

function placeholderJavaModel() {
    return `// ${MARKER}\n`;
}

function placeholderSoundCatalog(file) {
    const sounds = readJson(file);
    for (const event of Object.values(sounds)) event.sounds = [];
    return stableJson(sounds);
}

function writeTarget(target) {
    const file = path.join(ROOT, target.path);
    if (target.kind === 'texture-png') writePng(file, placeholderPng(file));
    else if (target.kind === 'texture-metadata') {
        fs.writeFileSync(file, placeholderTextureMetadata(), 'utf8');
    }
    else if (target.kind === 'sound-ogg-removed' || target.kind === 'asset-archive-removed') {
        fs.rmSync(file, { force: true });
    }
    else if (target.kind === 'model-geo') fs.writeFileSync(file, placeholderGeo(file), 'utf8');
    else if (target.kind === 'model-obj') fs.writeFileSync(file, placeholderObj(file), 'utf8');
    else if (target.kind === 'model-mtl') fs.writeFileSync(file, placeholderMtl(), 'utf8');
    else if (target.kind === 'legacy-java-model') fs.writeFileSync(file, placeholderJavaModel(), 'utf8');
    else if (target.kind === 'sound-catalog') fs.writeFileSync(file, placeholderSoundCatalog(file), 'utf8');
    else if (target.kind === 'modern-java-model') { /* Checked below; maintained as normal source. */ }
    else fs.writeFileSync(file, expectedJson(target.kind), 'utf8');
}

function isPlaceholder(target) {
    const file = path.join(ROOT, target.path);
    if (target.kind === 'sound-ogg-removed' || target.kind === 'asset-archive-removed') {
        return !fs.existsSync(file);
    }
    if (!fs.existsSync(file)) return false;
    if (target.kind === 'texture-png') {
        const actual = readPng(file);
        const expected = placeholderPng(file);
        return actual.width === target.width && actual.height === target.height
            && actual.width === expected.width && actual.height === expected.height
            && actual.pixels.equals(expected.pixels);
    }
            if (target.kind === 'texture-metadata') return fs.readFileSync(file, 'utf8') === placeholderTextureMetadata();
    const actual = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
    if (target.kind === 'model-geo') {
        const parsed = readJson(file);
        const geometry = parsed['minecraft:geometry']?.[0];
        const actualBones = (geometry?.bones || []).map(bone => bone.name)
            .filter(name => name !== 'placeholder_root').sort();
        return parsed.format_version === '1.12.0'
            && geometry?.description?.identifier === 'geometry.abyssalcraft.placeholder'
            && geometry?.bones?.[0]?.name === 'placeholder_root'
            && JSON.stringify(actualBones) === JSON.stringify(target.requiredBones || [])
            && geometry.bones.every(bone => bone.name === 'placeholder_root'
                || (bone.parent === 'placeholder_root'
                    && JSON.stringify(bone.pivot) === '[0,0,0]'
                    && bone.cubes === undefined));
    }
    if (target.kind === 'model-obj') return actual === placeholderObj(file);
    if (target.kind === 'model-mtl') return actual === placeholderMtl();
    if (target.kind === 'legacy-java-model') return actual === placeholderJavaModel();
    if (target.kind === 'sound-catalog') {
        const sounds = readJson(file);
        return JSON.stringify(Object.keys(sounds).sort()) === JSON.stringify(target.requiredEvents || [])
            && Object.values(sounds).every(event => Array.isArray(event.sounds) && event.sounds.length === 0);
    }
    if (target.kind === 'modern-java-model') {
        return actual.includes('License-safe')
            && !actual.includes('1.12.2')
            && (actual.match(/\.addBox\(/g) || []).length <= 6;
    }
    return actual === expectedJson(target.kind);
}

const discovered = discoverTargets();
if (mode === '--write') {
    for (const target of discovered) writeTarget(target);
    const manifest = {
        schema: 1,
        policy: 'LICENSE_ASSETS.md: original textures, models, and sounds are replaced in-place.',
        marker: MARKER,
        soundPolicy: 'Event IDs remain registered with empty sample arrays; production OGG files are removed.',
        licenseSafeTextureExclusions: [...LICENSE_SAFE_TEXTURES].sort(),
        targets: discovered,
    };
    fs.mkdirSync(path.dirname(MANIFEST), { recursive: true });
    fs.writeFileSync(MANIFEST, stableJson(manifest), 'utf8');
}

if (!fs.existsSync(MANIFEST)) {
    console.error(`Restricted asset placeholder manifest missing; discovered=${discovered.length}`);
    process.exit(1);
}

const manifest = readJson(MANIFEST);
const manifestTargets = manifest.targets || [];
const discoveredPaths = new Set(discovered.map(target => `${target.kind}:${target.path}`));
const manifestPaths = new Set(manifestTargets.map(target => `${target.kind}:${target.path}`));
const scopeDrift = [...discoveredPaths].filter(target => !manifestPaths.has(target))
    .concat([...manifestPaths].filter(target => !discoveredPaths.has(target)));
const invalid = manifestTargets.filter(target => !isPlaceholder(target));
if (scopeDrift.length || invalid.length) {
    if (scopeDrift.length) console.error(`Restricted asset placeholder scope drift:\n${scopeDrift.join('\n')}`);
    if (invalid.length) console.error(`Restricted assets not replaced:\n${invalid.map(target => target.path).join('\n')}`);
    process.exit(1);
}

const counts = Object.fromEntries([...new Set(manifestTargets.map(target => target.kind))]
    .sort().map(kind => [kind, manifestTargets.filter(target => target.kind === kind).length]));
console.log(`RR_RESTRICTED_ASSET_PLACEHOLDERS_OK targets=${manifestTargets.length} counts=${JSON.stringify(counts)}`);